### PR TITLE
Install nltk stopwords

### PR DESCRIPTION
**Pull request by ngpgn**
To address issue #14 for users unaware of nltk stopwords.
Included (optional) image nltk_downloader.jpg to "hand-hold" first-time users, 
but the image can be linked in tutorials/README.md only after it's merged in master branch

### CODE REVIEW

**Comment by postalC** [comment]
@seansaito, @wangjin1024  any idea what the Travis CI is waiting for?

**Comment by postalC** [comment]
> @seansaito, @wangjin1024 any idea what the Travis CI is waiting for?

found the solution - https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by postalC** [comment]
@ngpgn the check is passed, added reviewer, thanks

**Review by postalC — APPROVED** [review]
Thanks

**Review by wangjin1024 — APPROVED** [review]

**Pull request merged**
